### ISSUE TITLE
qg.installShortcut的success和fail有问题

### ISSUE THREAD

**Issue by shuizhongyueming** [oppominigame/issues#1]
### 相关信息
- 问题类型

引擎

- 引擎版本

oppo 1060

- 手机型号

OPPO A11

- 操作系统

windows 10

### 问题描述

qg.installShortcut(object)

属性 | 键值类型 | 是否必填 | 说明
-- | -- | -- | --
success | function | 否 | 接口调用成功的回调函数
fail | function | 否 | 接口调用失败的回调函数
complete | function | 否 | 接口调用结束的回调函数

这个接口在实际测试的时候，success回调会在添加桌面图标的确认弹窗出现的时候调用。但是我认为在确认弹窗里面，选择添加，并最终成功安装上桌面图标之后再调用success才正确。fail回调，本来以为再确认弹窗里面选择取消的时候会触发，但是一直没有触发

**Comment by zyqq** [comment]
这个是历史遗留问题，我们在4.0快应用版本的包修复了哈，预计12月初全量；因为installShortcut不管点击确认或者取消都会调用成功回调，所以现在暂时可以在成功回调里面设置setTimeout以及结合hasShortcutInstalled来判断用户是否真正创建了桌面图标
