### ISSUE TITLE
[object Object]无法转换

### ISSUE THREAD

**Issue by linfubao** [oppominigame/issues#20]
真机测试下通过setEnableDebug打开enableDebug, 为什么原生广告onError返回的数据显示一直是[object Object] , json也转不过来 , 奇了怪了 , 你们到底返回的是个啥 , 请指教!!!! 如果能转换 , 请帮忙解答一下你们是怎么转换成正常的对象显示的????

**Comment by zyqq** [comment]
麻烦提供截图以及代码

**Comment by linfubao** [comment]
![1631957675(1)](https://user-images.githubusercontent.com/61309442/133884385-2134e17f-b720-4795-8475-2b5b69938ea2.png)
![代码](https://user-images.githubusercontent.com/61309442/133884426-5716f692-38d2-418c-bd06-1d1cabc5afca.jpg)

**Comment by zyqq** [comment]
直接打印err呢

**Comment by linfubao** [comment]
都一样,  转不转json都是显示[object Object] , 所以我才奇怪到底怎么回事 , 你们测试的时候能正常打印????

**Comment by zyqq** [comment]
麻烦提供一下快应用版本号

**Comment by linfubao** [comment]
runtime_v430 / runtime_v450

**Comment by zyqq** [comment]
![Image_20210918180601](https://user-images.githubusercontent.com/15664576/133885244-68012478-f51a-41d5-83b5-35101209599a.png)
![Image_20210918180613](https://user-images.githubusercontent.com/15664576/133885247-ccc6521f-3a4e-4409-a65f-182a28ec5335.png)
这边试了4.5是没有问题的哦，建议你再用promise回调试一下
