### ISSUE TITLE
拉取广告以后，没反应也不报错，onload和onerror也没进去，oppo手机和云真机上都是这样

### ISSUE THREAD

**Issue by zw1040954319** [oppominigame/issues#6]
![图片](https://user-images.githubusercontent.com/48433193/105449879-38b22600-5cb4-11eb-8484-6176c08051ce.png)
        var self = this;
        _bannerAd = qg.createBannerAd({
            posId: 'xxxxxx',
            style: {
                top: 300,
                left: 0,
                width: 900,
                height: 300
            }
        })

        _bannerAd.show()

        _bannerAd.onLoad(function () {
            console.log('banner 广告加载成功')
        })
        _bannerAd.onError(function () {
            console.log('banner 广告加载失败')
        })

        this.scheduleOnce(function () {
            self.showlog();
            _bannerAd.show()
        }, 2);

**Comment by DuanPengZhanxx** [comment]
加群解决549663152   或者加我个人QQ3004677539
