### ISSUE TITLE
设置banner位置有的手机生效, 有的手机不生效

### ISSUE THREAD

**Issue by linfubao** [oppominigame/issues#7]
### 相关信息
- 问题类型: 不清楚

- 引擎版本

- 手机型号: oppo reno

- 操作系统

- IDE版本

- toolkit版本

### 问题描述
设置banner位置时 , 有的手机会生效, 有的手机不生效, 不生效是指一直在屏幕底部 , 无法改变尺寸和坐标位置 

### 复现步骤

最小平台版本号: 1060
this.bannerAd = qg.createBannerAd({
        adUnitId: this.bannerId,
        style: {
            top: 0,
            left: 0,
            width: 900,
            height: 300
        }
  })
this.bannerAd.onResize(function (obj) {
        this.bannerAd.style = {
            top:0
            left: 0,
            width: 900,
            height: 300
        }
});

### 联系方式
微信号: LFB474521876

**Comment by DuanPengZhanxx** [comment]
banner一般推荐是在屏幕底部，如果你想改变位置的话，建议把banner做成原生banner
