### ISSUE TITLE
你们的快游戏调试器是来搞笑的吗，更新到新版本，桌面上图标都没有，叫我去哪里打开调试器呢？？？！！！！

### ISSUE THREAD

**Issue by mrliugithub** [oppominigame/issues#9]
### 相关信息
- 问题类型

- 引擎版本

- 手机型号

- 操作系统

- IDE版本

- toolkit版本

**Comment by DuanPengZhanxx** [comment]
麻烦把相关信息描述清楚，  关掉软件商店WiFi情况下自动更新  快应用即不会自动升级

**Comment by G96968586** [comment]
这是由于软件商店自动更新，把线上的版本覆盖了调试器的版本，而线上的版本不会在系统桌面上创建 icon，所以导致你这边找不到了。推荐在软件商店上关闭对快应用的自动更新哈。后面我们会优化这个问题。
